create_pages:
    script:
        - jekyll build
    only:
        - master
    stage:
        build
deploy_pages:
    script:
        - jekyll build
        - cp -r _site/* /opt/apache/htdocs/doc/TODO/
    only:
        - master
    stage:
        deploy
